### PR TITLE
Enable ssl

### PR DESCRIPTION
**Pull request by zsoerenm**
Some options need to be changed to enable SSL:

https://manual.seafile.com/deploy/https_with_nginx.html

### CODE REVIEW

**Comment by zsoerenm** [comment]
I also made SERVER_ADDRESS be changeable after installation

**Comment by camory** [comment]
Thanks for this PR. I reviewed it and review the current code. I think we have a couple issues.
Updating `seahub_settings.py` to add `FILE_SERVER_ROOT` variable is already done with the current code. But it is only done when `FASTCGI`is activated which is a mistake.
About your PR, updating `seahub_settings.py` and `ccnet.conf`to add the url should not be done only SSL is enabled. It must be done when Seafile Server is behind a reverse proxy.

So we have to fix the current issue and update your PR. Here is what I am suggesting:
- Remove `fastcgi_conf()`function
- Rename `ENABLE_SSL` to `REVERSE_PROXY_MODE` which can take 2 values: `HTTP` or `HTTPS`. By default, it is equal to an empty string. `seahub_settings.py` and `ccnet.conf` files are updating only if `REVERSE_PROXY_MODE` is equal to HTTP or HTTPS.
- Update the README.md 
- Optional: only expose seahub/media if `REVERSE_PROXY_MODE` is equal to HTTP or HTTPS. This folder must be used by the reverse proxy. It is not an issue if this folder is always expose. It allows people to update images or css but we have to warn the user (in the README.md and ask confimation in `upgrade` script) that this folder will be updated and any change will be lost.

So this can be done in this PR or we can close it and open a new one.

**Review by camory — CHANGES_REQUESTED** [review]
Thanks for this PR. I reviewed it and review the current code. I think we have a couple issues.
Updating `seahub_settings.py` to add `FILE_SERVER_ROOT` variable is already done with the current code. But it is only done when `FASTCGI` is activated which is a mistake.
About your PR, updating `seahub_settings.py` and `ccnet.conf` to add the url should not be done only when SSL is enabled. It must be done when Seafile Server is behind a reverse proxy.

So we have to fix the current issue and update your PR. Here is what I am suggesting:

- Remove `fastcgi_conf()` function

 - Rename `ENABLE_SSL` to `REVERSE_PROXY_MODE` which can take 2 values: `HTTP` or `HTTPS`. By default, it is equal to an empty string. seahub_settings.py and ccnet.conf files are updating only if `REVERSE_PROXY_MODE` is equal to `HTTP` or `HTTPS`.
 - Update the `README.md`
 - Optional: only expose `seahub/media` if `REVERSE_PROXY_MODE` is equal to `HTTP` or `HTTPS`. This folder must be used by the reverse proxy. It is not an issue if this folder is always expose. It allows people to update images or css but we have to warn the user (in the `README.md` and ask confimation in `upgrade` script) that this folder will be updated and any change will be lost.

So this can be done in this PR or we can close it and open a new one.

**Comment by camory** [comment]
ssl is now managed since version 6.1.2-2

**Pull request closed without merging**
